[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://mcpress-chatbot-production-569b.up.railway.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://mcpress-chatbot-production-569b.up.railway.app/:splat"
  status = 200
  force = true