[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs"]
aptPkgs = ["tesseract-ocr", "build-essential"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm install --prefix frontend",
    "npm run build --prefix frontend"
]

[variables]
RAILWAY_ENVIRONMENT = "false"
DATA_DIR = "/tmp/data"
NODE_ENV = "production"

[start]
cmd = "python3 start_railway_fullstack.py"