# Force both Python and Node.js providers
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18", "npm-9_x"]
aptPkgs = ["tesseract-ocr"]

[phases.install]
cmds = [
    "python3 -m pip install -r requirements.txt",
    "cd frontend && npm install"
]

[variables]
RAILWAY_ENVIRONMENT = "false"
DATA_DIR = "/tmp/data"

[start]
cmd = "python3 start_railway_fullstack.py"