[phases.setup]
nixPkgs = ["python310", "gcc", "tesseract", "poppler_utils", "postgresql", "pkg-config"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"