[phases.setup]
aptPkgs = ["tesseract-ocr"]

[phases.install]
# Install Node.js for frontend build
cmds = ["curl -fsSL https://deb.nodesource.com/setup_18.x | bash -", "apt-get install -y nodejs"]

[variables]
# Force ChromaDB usage (prevent PostgreSQL detection)
RAILWAY_ENVIRONMENT = "false"