[build]
builder = "nixpacks"

[build.env]
# Python/ML optimizations
SENTENCE_TRANSFORMERS_HOME = "/tmp"
HF_HOME = "/tmp"
TRANSFORMERS_CACHE = "/tmp"
HF_DATASETS_OFFLINE = "1"
TRANSFORMERS_OFFLINE = "1"

# Next.js optimizations
NEXT_TELEMETRY_DISABLED = "1"
SKIP_TYPE_CHECK = "true"

[deploy]
# Start both services with a process manager
startCommand = "python start_railway_fullstack.py"