[build]
builder = "nixpacks"

[build.env]
SENTENCE_TRANSFORMERS_HOME = "/tmp"
HF_HOME = "/tmp"
TRANSFORMERS_CACHE = "/tmp"
HF_DATASETS_OFFLINE = "1"
TRANSFORMERS_OFFLINE = "1"

[deploy]
startCommand = "python3 start_railway_fullstack.py"