"""
Data models for conversation export (Story-012)
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
from pydantic import BaseModel


class ExportOptions(BaseModel):
    """Options for customizing exports"""
    custom_title: Optional[str] = None
    subtitle: Optional[str] = None
    include_toc: bool = False
    include_timestamps: bool = True
    footer: Optional[str] = None
    page_size: str = "letter"
    margin: str = "1in"
    font_size: str = "11pt"


class CodeBlock(BaseModel):
    """Represents a code block in a message"""
    language: str
    code: str


class BookReference(BaseModel):
    """Book reference metadata"""
    title: str
    author: str


class FormattedMessage(BaseModel):
    """Formatted message for export"""
    role: str
    content: str
    code_blocks: List[CodeBlock] = []
    book_references: List[BookReference] = []
    timestamp: Optional[datetime] = None


class ExportData(BaseModel):
    """Structured data for export generation"""
    title: str
    subtitle: Optional[str] = None
    metadata: Dict[str, Any]
    messages: List[FormattedMessage]
    table_of_contents: bool = False
    footer: str = "Generated by MC Press Chatbot"


class ExportResult(BaseModel):
    """Result of an export operation"""
    id: Optional[str] = None
    filename: str
    file_data: bytes
    mime_type: str
    size: int


class ExportRequest(BaseModel):
    """Request to export a conversation"""
    conversation_id: str
    format: str = "pdf"  # pdf or markdown
    options: Optional[ExportOptions] = None


class BulkExportRequest(BaseModel):
    """Request to export multiple conversations"""
    conversation_ids: List[str]
    format: str = "pdf"
    options: Optional[ExportOptions] = None
