"""
Unit tests for Story-012 Export Service
"""

import asyncio
from datetime import datetime
from export_models import ExportOptions, CodeBlock
from markdown_generator import MarkdownGenerator
from pdf_generator import PDFGenerator
from export_models import ExportData, FormattedMessage


class TestMarkdownGenerator:
    """Test markdown export generation"""

    async def test_basic_markdown_export(self):
        """Test basic markdown export with minimal data"""
        generator = MarkdownGenerator()

        export_data = ExportData(
            title="Test Conversation",
            subtitle=None,
            metadata={
                'created_at': datetime(2024, 1, 1, 12, 0),
                'message_count': 2,
                'tags': ['test', 'demo']
            },
            messages=[
                FormattedMessage(
                    role='user',
                    content='Hello, how are you?',
                    code_blocks=[],
                    book_references=[],
                    timestamp=datetime(2024, 1, 1, 12, 0)
                ),
                FormattedMessage(
                    role='assistant',
                    content='I am doing well, thank you!',
                    code_blocks=[],
                    book_references=[],
                    timestamp=datetime(2024, 1, 1, 12, 1)
                )
            ],
            footer="Generated by MC Press Chatbot"
        )

        options = ExportOptions(include_timestamps=True)
        result = await generator.generate(export_data, options)

        # Verify result
        assert isinstance(result, bytes)
        content = result.decode('utf-8')

        # Check key elements
        assert 'Test Conversation' in content
        assert '---' in content  # YAML front matter
        assert 'Hello, how are you?' in content
        assert 'I am doing well, thank you!' in content
        assert '👤 User' in content
        assert '🤖 Assistant' in content

    async def test_markdown_with_code_blocks(self):
        """Test markdown export with code blocks"""
        generator = MarkdownGenerator()

        export_data = ExportData(
            title="Code Example",
            metadata={
                'created_at': datetime(2024, 1, 1),
                'message_count': 1
            },
            messages=[
                FormattedMessage(
                    role='assistant',
                    content='Here is a Python example:',
                    code_blocks=[
                        CodeBlock(language='python', code='def hello():\n    print("Hello")')
                    ],
                    book_references=[]
                )
            ],
            footer="Test"
        )

        options = ExportOptions()
        result = await generator.generate(export_data, options)
        content = result.decode('utf-8')

        # Verify code is present
        assert 'Here is a Python example:' in content


class TestPDFGenerator:
    """Test PDF export generation"""

    async def test_pdf_html_generation(self):
        """Test HTML generation for PDF (fallback mode)"""
        generator = PDFGenerator()

        export_data = ExportData(
            title="PDF Test",
            metadata={
                'created_at': datetime(2024, 1, 1),
                'message_count': 1
            },
            messages=[
                FormattedMessage(
                    role='user',
                    content='Test message',
                    code_blocks=[],
                    book_references=[]
                )
            ],
            footer="Test Footer"
        )

        options = ExportOptions()
        result = await generator.generate(export_data, options)

        # Verify result (will be HTML if WeasyPrint not available)
        assert isinstance(result, bytes)
        content = result.decode('utf-8')
        assert 'PDF Test' in content
        assert 'Test message' in content


class TestExportService:
    """Test complete export service"""

    def test_code_block_extraction(self):
        """Test extraction of code blocks from content"""
        from export_service import ConversationExportService

        # Mock conversation service
        class MockConversationService:
            pass

        # Mock vector store
        class MockVectorStore:
            pool = None

        service = ConversationExportService(
            MockConversationService(),
            MockVectorStore()
        )

        content = """
Here is some code:

```python
def hello():
    print("Hello World")
```

And more text here.
"""

        code_blocks = service._extract_code_blocks(content)
        assert len(code_blocks) == 1
        assert code_blocks[0].language == 'python'
        assert 'def hello' in code_blocks[0].code

    def test_filename_sanitization(self):
        """Test filename sanitization"""
        from export_service import ConversationExportService

        class MockConversationService:
            pass

        class MockVectorStore:
            pool = None

        service = ConversationExportService(
            MockConversationService(),
            MockVectorStore()
        )

        # Test various problematic filenames
        assert service._sanitize_filename("Normal Name") == "Normal Name"
        assert service._sanitize_filename("Name/With/Slashes") == "Name_With_Slashes"
        assert service._sanitize_filename("Name:With:Colons") == "Name_With_Colons"
        assert service._sanitize_filename("A" * 300)  # Long name
        assert len(service._sanitize_filename("A" * 300)) <= 200


if __name__ == "__main__":
    # Run basic tests
    print("🧪 Running export service tests...")

    # Test markdown generator
    print("\n1. Testing Markdown Generator...")
    try:
        test = TestMarkdownGenerator()
        asyncio.run(test.test_basic_markdown_export())
        print("   ✅ Basic markdown export test passed")

        asyncio.run(test.test_markdown_with_code_blocks())
        print("   ✅ Markdown with code blocks test passed")
    except Exception as e:
        print(f"   ❌ Markdown generator test failed: {e}")

    # Test PDF generator
    print("\n2. Testing PDF Generator...")
    try:
        test = TestPDFGenerator()
        asyncio.run(test.test_pdf_html_generation())
        print("   ✅ PDF HTML generation test passed")
    except Exception as e:
        print(f"   ❌ PDF generator test failed: {e}")

    # Test export service
    print("\n3. Testing Export Service...")
    try:
        test = TestExportService()
        test.test_code_block_extraction()
        print("   ✅ Code block extraction test passed")

        test.test_filename_sanitization()
        print("   ✅ Filename sanitization test passed")
    except Exception as e:
        print(f"   ❌ Export service test failed: {e}")

    print("\n✅ All export tests completed!")
